# Generated by Django 4.0.6 on 2022-10-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_todolist_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
